# Generated by Django 5.1.5 on 2025-02-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unloc_code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                ("province", models.CharField(blank=True, max_length=100, null=True)),
                ("timezone", models.CharField(max_length=50)),
                ("alias", models.JSONField(default=list)),
                ("regions", models.JSONField(default=list)),
                ("coordinates_lat", models.FloatField(blank=True, null=True)),
                ("coordinates_lon", models.FloatField(blank=True, null=True)),
                ("code", models.CharField(max_length=10)),
            ],
        ),
    ]
