# Generated by Django 5.1.5 on 2025-02-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0003_rename_citytion_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
