# Generated by Django 5.1.5 on 2025-02-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0004_alter_city_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="timezone",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
