# Generated by Django 5.1.5 on 2025-02-07 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0005_alter_city_timezone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
    ]
